name: CI

on: [push]

jobs:
  build:

    container: 
      image: mcr.microsoft.com/dotnet/core/sdk:3.0.100-rc1-disco

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        dotnet new classlib
        dotnet build
